<span style="color:green;"></span> <span style="color:#00ff00;">[2025-03-22 00:21:50H] [General] qweqweqw</span>
<span style="color:red;">★</span> <span style="color:#00ff00;">[2025-03-22 00:22:34H] [General] qweqweqwe</span>
<span style="color:yellow;">■</span> <span style="color:#00ff00;">[2025-03-22 00:22:37H] [General] wwww</span>
<span style="color:black;">▲</span> <span style="color:#00ff00;">[2025-03-22 00:22:40H] [General] qweqwe</span>
<span style="color:blue;">◆</span> <span style="color:#00ff00;">[2025-03-22 00:22:44H] [General] wwww</span>
<span style="color:blue;">◆</span> <span style="color:#00ff00;">[2025-03-22 00:22:46H] [Debugging] wwww - MemUsage: 6000/8150MB (73.6% used), CPU Usage: 18.9%, GPU Usage: Error (Not Supported)</span>
<span style="color:blue;">◆</span> <span style="color:#00ff00;">[2025-03-22 00:23:06H] [General] www - User: Mathew</span>
<span style="color:green;"></span> <span style="color:#00ff00;">[2025-03-22 00:52:18H] [General] qweqweqwe</span>
<span style="color:blue;">◆</span> <span style="color:#00ff00;">[2025-03-22 00:59:24] [General] weqwe  -Edited</span>
